# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f13f34ee61320791d25b8cff02943740cacac6304ca1a10e851f285c8f6a8d93d705a62f0c9445c8aef683ef140a2504212478b0db8909608d3f4c678916c4d

test:
  secret_key_base: 0fe618797c1259520b9af0de3aebfee14b967da3452f694b508cf1adb726fc53c196b35803b4f676effaeefe9fed000e86e46d9979c8dfc2983db874738a435b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
